# vim: set ft=dosini
---
version: '3'
services:
  bedrock:
    build:
      context: ./docker/bedrock
    restart: always
    container_name: bedrock
    hostname: bedrock
    volumes:
      - ./docker/runtime/db:/bedrock

  php-fpm:
    build:
      context: ./docker/php-fpm
    restart: always
    container_name: php-fpm
    hostname: php-fpm
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/runtime/logs:/logs

  nginx:
    restart: always
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    links:
      - php-fpm
    ports:
      - 32765:80
    volumes:
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
